# Generated by Django 2.2 on 2019-05-04 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Allin_Test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Questions', models.TextField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Zip_File', models.FileField(upload_to='candidate/solutions/')),
                ('Video_File', models.FileField(upload_to='candidate/video_solutions/')),
                ('inform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Allin_Test.Information')),
            ],
        ),
    ]
