# Generated by Django 2.2 on 2019-05-05 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Allin_Test', '0003_auto_20190505_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='inform',
        ),
    ]
