# Generated by Django 2.2 on 2019-05-05 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Allin_Test', '0004_remove_solution_inform'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='Full_Name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
