# Generated by Django 2.2 on 2019-05-05 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Allin_Test', '0008_solution_result'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Information',
        ),
    ]
