# Generated by Django 2.2 on 2019-05-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Allin_Test', '0009_delete_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True, unique=True),
        ),
    ]
