# Generated by Django 2.2 on 2019-05-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Allin_Test', '0010_solution_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='email',
            field=models.EmailField(blank=True, default='jainhardik255@gmail.com', max_length=70, null=True, unique=True),
        ),
    ]
